### ISSUE TITLE
Weird syntax highlighting

### ISSUE THREAD

**Issue by Ayutac** [moschlar/SAUCE#235]
Okay, I have no idea why this happens. Have a look at submission 13598. In the second class, there is a method deselect. in line 50 it's used and clearly not highlighted, but in line 51 it is (but shouldn't of course).

**Comment by moschlar** [comment]
Indeed, that's strange. But I think in line 51, it should definitely not be highlighted in blue, since that would be the color for the method definition.

**Comment by Ayutac** [comment]
Oh look, I found another!
Submission 15817

**Comment by moschlar** [comment]
Ah, okay, I think it's due to the fact that the outer scaffold is missing from the highlighted snippet, which confuses the parser... (compare the full source view to the one in the development instance).
Because the new version will use a different syntax highlighter and will display the full source including the scaffold, this can be considered fixed - as soon as the new version is ready...
